export const ipcChannels = {
  ping: 'app:ping',
  getAppVersion: 'app:get-version',
  login: 'auth:login',
  logout: 'auth:logout',
  getSession: 'auth:get-session',
  userList: 'user:list',
  userAdd: 'user:add',
  userUpdate: 'user:update',
  userDelete: 'user:delete',
  scanRun: 'scan:run',
  scanHostFound: 'scan:host-found',
  scanAddToAssets: 'scan:add-to-assets',
  assetList: 'asset:list',
  assetUpdate: 'asset:update',
  assetDelete: 'asset:delete',
  categoryList: 'category:list',
  categoryAdd: 'category:add',
  categoryUpdate: 'category:update',
  categoryDelete: 'category:delete',
  locationList: 'location:list',
  locationAdd: 'location:add',
  locationUpdate: 'location:update',
  locationDelete: 'location:delete',
  companyGet: 'company:get',
  companyUpdate: 'company:update',
  assetsCheckAccessibility: 'assets:check-accessibility',
  assetsWinrmProgress: 'assets:winrm-progress',
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
