export const ipcChannels = {
  ping: 'app:ping',
  getAppVersion: 'app:get-version',
  getDatabaseStatus: 'app:get-database-status',
  login: 'auth:login',
  logout: 'auth:logout',
  getSession: 'auth:get-session',
  assetList: 'asset:list',
  assetGet: 'asset:get',
  assetUpdate: 'asset:update',
  assetDelete: 'asset:delete',
  assetDeleteMany: 'asset:delete-many',
  winrmBatch: 'winrm:batch',
  winrmProgress: 'winrm:progress',
  locationList: 'location:list',
  locationAdd: 'location:add',
  locationDelete: 'location:delete',
  groupList: 'group:list',
  groupAdd: 'group:add',
  groupRename: 'group:rename',
  groupDelete: 'group:delete',
  assessModuleList: 'assess:module-list',
  assessModuleSave: 'assess:module-save',
  assessModuleDelete: 'assess:module-delete',
  assessRun: 'assess:run',
  assessHistory: 'assess:history',
  assessResult: 'assess:result',
  assessReverse: 'assess:reverse',
  findingsMatrix: 'findings:matrix',
  scanAuthorizedRanges: 'scan:authorized-ranges',
  scanRun: 'scan:run',
  scanHostFound: 'scan:host-found',
  nmapProtocolRun: 'nmap:protocol-run',
  nmapProtocolGet: 'nmap:protocol-get',
  nvdStatus: 'nvd:status',
  nvdSaveKey: 'nvd:save-key',
  nvdSync: 'nvd:sync',
  nvdSoftwareHits: 'nvd:software-hits',
  companyGet: 'company:get',
  companySaveName: 'company:save-name',
  companyUploadLogo: 'company:upload-logo',
  companyRemoveLogo: 'company:remove-logo',
  auditList: 'audit:list',
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
