export type BaselineStatus = 'pass' | 'warn' | 'fail' | 'skip';

export type BaselineCheck = {
  id: string;
  title: string;
};

export const BASELINE_CHECKS: BaselineCheck[] = [
  { id: 'password_complexity', title: 'Password complexity enabled' },
  { id: 'min_password_length', title: 'Minimum password length >= 14' },
  { id: 'password_history', title: 'Password history >= 10' },
  { id: 'account_lockout', title: 'Account lockout policy configured' },
  { id: 'guest_disabled', title: 'Guest account disabled' },
  { id: 'unused_local_accounts', title: 'Unused local accounts disabled' },
  { id: 'excessive_local_admins', title: 'No more than 3 local administrators' },
  { id: 'uac_enabled', title: 'UAC enabled' },
  { id: 'firewall_enabled', title: 'Windows Firewall enabled' },
  { id: 'defender_realtime', title: 'Windows Defender real-time protection enabled' },
  { id: 'defender_tamper', title: 'Defender Tamper Protection enabled' },
  { id: 'security_updates_current', title: 'Windows Security updates current' },
  { id: 'smbv1_enabled', title: 'SMBv1 disabled' },
  { id: 'smb_signing', title: 'SMB signing required' },
  { id: 'anonymous_smb', title: 'Anonymous SMB access disabled' },
  { id: 'excessive_smb_share_perms', title: 'SMB share permissions restricted' },
  { id: 'everyone_sensitive_shares', title: 'Sensitive shares not accessible by Everyone' },
  { id: 'llmnr_enabled', title: 'LLMNR disabled' },
  { id: 'netbios_tcpip', title: 'NetBIOS over TCP/IP disabled' },
  { id: 'tls10_enabled', title: 'TLS 1.0 disabled' },
  { id: 'tls11_enabled', title: 'TLS 1.1 disabled' },
  { id: 'ssl3_enabled', title: 'SSL 3.0 disabled' },
  { id: 'powershell_logging', title: 'PowerShell logging enabled' },
  { id: 'powershell_v2', title: 'PowerShell v2 disabled' },
  { id: 'winrm_exposed_lan', title: 'WinRM not exposed to the entire LAN' },
  { id: 'winrm_restricted', title: 'WinRM restricted' },
  { id: 'rdp_exposed_lan', title: 'RDP not exposed to the entire LAN' },
  { id: 'rdp_nla', title: 'RDP Network Level Authentication enabled' },
  { id: 'rdp_enabled', title: 'RDP disabled unless required' },
  { id: 'unnecessary_listening_ports', title: 'No unnecessary listening ports' },
  { id: 'telnet_enabled', title: 'Telnet service disabled' },
  { id: 'ftp_enabled', title: 'FTP service disabled' },
  { id: 'unnecessary_services', title: 'Unnecessary Windows services disabled' },
  { id: 'secure_boot', title: 'Secure Boot enabled' },
  { id: 'tpm_enabled', title: 'TPM enabled' },
  { id: 'bitlocker_enabled', title: 'BitLocker enabled' },
  { id: 'bitlocker_recovery_backup', title: 'BitLocker recovery key backed up' },
  { id: 'screen_lock', title: 'Automatic screen lock enabled' },
  { id: 'screen_lock_timeout', title: 'Screen lock timeout <= 15 minutes' },
  { id: 'outdated_applications', title: 'Applications kept up to date' },
  { id: 'unsupported_software', title: 'No unsupported software installed' },
  { id: 'apps_known_cves', title: 'No applications with known CVEs' },
  { id: 'suspicious_startup', title: 'No suspicious startup applications' },
  { id: 'suspicious_tasks', title: 'No suspicious scheduled tasks' },
  { id: 'defender_enabled', title: 'Microsoft Defender enabled' },
  { id: 'defender_exclusions', title: 'Defender exclusions kept minimal' },
  { id: 'security_auditing', title: 'Security auditing enabled' },
  { id: 'failed_logon_auditing', title: 'Failed logon auditing enabled' },
  { id: 'account_mgmt_auditing', title: 'Account management auditing enabled' },
  { id: 'ps_operational_logging', title: 'PowerShell operational logging enabled' },
  { id: 'audit_log_retention', title: 'Audit log retention sufficient' },
  { id: 'null_session', title: 'Anonymous/null session access disabled' },
  { id: 'cached_domain_creds', title: 'Cached domain credentials configured securely' },
  { id: 'wdigest_caching', title: 'WDigest credential caching disabled' },
  { id: 'ntlm_usage', title: 'NTLM usage restricted' },
  { id: 'ldap_signing', title: 'LDAP signing enforced' },
  { id: 'ldap_channel_binding', title: 'LDAP channel binding enforced' },
  { id: 'admin_shares', title: 'Administrative shares restricted' },
  { id: 'unnecessary_admin_privs', title: 'No unnecessary administrative privileges' },
  { id: 'windows_update_enabled', title: 'Windows Update enabled' },
  { id: 'defender_intel_updates', title: 'Automatic security intelligence updates enabled' },
  { id: 'reboot_pending_updates', title: 'No reboot pending after security updates' },
  { id: 'unnecessary_adapters', title: 'Unnecessary network adapters disabled' },
  { id: 'wifi_on_server', title: 'Wi-Fi disabled on servers' },
  { id: 'bluetooth_enabled', title: 'Bluetooth disabled unless required' },
  { id: 'services_on_nics', title: 'No unnecessary services on network interfaces' },
  { id: 'dns_validated', title: 'DNS configuration validated' },
  { id: 'unauthorized_dns', title: 'Only authorized DNS servers' },
  { id: 'users_not_local_admins', title: 'Standard users have no local administrator privileges' },
  { id: 'service_interactive_logon', title: 'Service accounts have no interactive logon' },
  { id: 'secrets_in_scripts', title: 'No passwords or secrets in scripts' },
  { id: 'unencrypted_sensitive_files', title: 'No unencrypted sensitive files' },
  { id: 'backup_config', title: 'Backup configuration present' },
  { id: 'backup_dest_user_access', title: 'Backup destination not accessible to standard users' },
  { id: 'backup_restore_tested', title: 'Backup restore tested recently' },
  { id: 'bios_uefi_reviewed', title: 'BIOS/UEFI configuration reviewed' },
  { id: 'usb_external_boot', title: 'USB/external boot disabled' },
  { id: 'windows_version_supported', title: 'Windows version supported' },
  { id: 'architecture_supported', title: 'System architecture supported' },
  { id: 'unsupported_protocols', title: 'No unsupported protocols' },
  { id: 'unnecessary_open_ports', title: 'No unnecessary open ports' },
  { id: 'firewall_rules_reviewed', title: 'Host firewall rules reviewed' },
  { id: 'excessive_inbound_rules', title: 'Inbound firewall rules not excessive' },
  { id: 'any_any_inbound', title: 'No inbound firewall rule allows Any/Any' },
  { id: 'outdated_drivers', title: 'Drivers kept up to date' },
  { id: 'pending_reboot', title: 'No pending Windows reboot' },
];

export const SOFTWARE_CVE_CHECK_IDS = new Set([
  'apps_known_cves',
  'outdated_applications',
  'unsupported_software',
]);
