export type BaselineStatus = 'pass' | 'warn' | 'fail' | 'skip';

export type BaselineCheck = {
  id: string;
  title: string;
};

export const BASELINE_CHECKS: BaselineCheck[] = [
  { id: 'password_complexity', title: 'Password complexity enabled' },
  { id: 'min_password_length', title: 'Minimum password length >= 14' },
  { id: 'password_history', title: 'Password history >= 10' },
  { id: 'account_lockout', title: 'Account lockout policy configured' },
  { id: 'guest_disabled', title: 'Guest account disabled' },
  { id: 'unused_local_accounts', title: 'Unused local accounts disabled' },
  { id: 'excessive_local_admins', title: 'Excessive local administrators detected' },
  { id: 'uac_enabled', title: 'UAC enabled' },
  { id: 'firewall_enabled', title: 'Windows Firewall enabled' },
  { id: 'defender_realtime', title: 'Windows Defender real-time protection enabled' },
  { id: 'defender_tamper', title: 'Defender Tamper Protection enabled' },
  { id: 'security_updates_current', title: 'Windows Security updates current' },
  { id: 'smbv1_enabled', title: 'SMBv1 enabled' },
  { id: 'smb_signing', title: 'SMB signing required' },
  { id: 'anonymous_smb', title: 'Anonymous SMB access enabled' },
  { id: 'excessive_smb_share_perms', title: 'Excessive SMB share permissions detected' },
  { id: 'everyone_sensitive_shares', title: 'Sensitive shares accessible by Everyone' },
  { id: 'llmnr_enabled', title: 'LLMNR enabled' },
  { id: 'netbios_tcpip', title: 'NetBIOS over TCP/IP enabled' },
  { id: 'tls10_enabled', title: 'TLS 1.0 enabled' },
  { id: 'tls11_enabled', title: 'TLS 1.1 enabled' },
  { id: 'ssl3_enabled', title: 'SSL 3.0 enabled' },
  { id: 'powershell_logging', title: 'PowerShell logging enabled' },
  { id: 'powershell_v2', title: 'PowerShell v2 enabled' },
  { id: 'winrm_exposed_lan', title: 'WinRM exposed to entire LAN' },
  { id: 'winrm_restricted', title: 'WinRM restricted' },
  { id: 'rdp_exposed_lan', title: 'RDP exposed to entire LAN' },
  { id: 'rdp_nla', title: 'RDP Network Level Authentication enabled' },
  { id: 'rdp_enabled', title: 'RDP enabled' },
  { id: 'unnecessary_listening_ports', title: 'Unnecessary listening ports detected' },
  { id: 'telnet_enabled', title: 'Telnet service enabled' },
  { id: 'ftp_enabled', title: 'FTP service enabled' },
  { id: 'unnecessary_services', title: 'Unnecessary Windows services detected' },
  { id: 'secure_boot', title: 'Secure Boot enabled' },
  { id: 'tpm_enabled', title: 'TPM enabled' },
  { id: 'bitlocker_enabled', title: 'BitLocker enabled' },
  { id: 'bitlocker_recovery_backup', title: 'BitLocker recovery key not backed up' },
  { id: 'screen_lock', title: 'Automatic screen lock enabled' },
  { id: 'screen_lock_timeout', title: 'Screen lock timeout <= 15 minutes' },
  { id: 'outdated_applications', title: 'Outdated applications detected' },
  { id: 'unsupported_software', title: 'Unsupported software detected' },
  { id: 'apps_known_cves', title: 'Applications with known CVEs detected' },
  { id: 'suspicious_startup', title: 'Suspicious startup applications detected' },
  { id: 'suspicious_tasks', title: 'Suspicious scheduled tasks detected' },
  { id: 'defender_enabled', title: 'Microsoft Defender enabled' },
  { id: 'defender_exclusions', title: 'Excessive Defender exclusions detected' },
  { id: 'security_auditing', title: 'Security auditing enabled' },
  { id: 'failed_logon_auditing', title: 'Failed logon auditing enabled' },
  { id: 'account_mgmt_auditing', title: 'Account management auditing enabled' },
  { id: 'ps_operational_logging', title: 'PowerShell operational logging enabled' },
  { id: 'audit_log_retention', title: 'Audit logs retention insufficient' },
  { id: 'null_session', title: 'Anonymous/null session access enabled' },
  { id: 'cached_domain_creds', title: 'Cached domain credentials configuration requires review' },
  { id: 'wdigest_caching', title: 'WDigest credential caching enabled' },
  { id: 'ntlm_usage', title: 'NTLM usage detected' },
  { id: 'ldap_signing', title: 'LDAP signing not enforced' },
  { id: 'ldap_channel_binding', title: 'LDAP channel binding not enforced' },
  { id: 'admin_shares', title: 'Unrestricted administrative shares detected' },
  { id: 'unnecessary_admin_privs', title: 'Users with unnecessary administrative privileges detected' },
  { id: 'windows_update_enabled', title: 'Windows Update enabled' },
  { id: 'defender_intel_updates', title: 'Automatic security intelligence updates enabled' },
  { id: 'reboot_pending_updates', title: 'Reboot pending after security updates' },
  { id: 'unnecessary_adapters', title: 'Unnecessary network adapters enabled' },
  { id: 'wifi_on_server', title: 'Wi-Fi enabled on server' },
  { id: 'bluetooth_enabled', title: 'Bluetooth enabled' },
  { id: 'services_on_nics', title: 'Unnecessary services listening on network interfaces' },
  { id: 'dns_validated', title: 'DNS configuration validated' },
  { id: 'unauthorized_dns', title: 'Unauthorized DNS servers detected' },
  { id: 'users_not_local_admins', title: 'Standard users have no local administrator privileges' },
  { id: 'service_interactive_logon', title: 'Service accounts with interactive logon rights detected' },
  { id: 'secrets_in_scripts', title: 'Passwords/secrets found in scripts or configuration files' },
  { id: 'unencrypted_sensitive_files', title: 'Unencrypted sensitive files detected' },
  { id: 'backup_config', title: 'Backup configuration detected' },
  { id: 'backup_dest_user_access', title: 'Backup destination accessible from normal user accounts' },
  { id: 'backup_restore_tested', title: 'Backup restore not recently tested' },
  { id: 'bios_uefi_reviewed', title: 'BIOS/UEFI configuration reviewed' },
  { id: 'usb_external_boot', title: 'USB/external boot enabled' },
  { id: 'windows_version_supported', title: 'Windows version supported' },
  { id: 'architecture_supported', title: 'System architecture supported' },
  { id: 'unsupported_protocols', title: 'Unsupported protocols detected' },
  { id: 'unnecessary_open_ports', title: 'Unnecessary open ports detected' },
  { id: 'firewall_rules_reviewed', title: 'Host firewall rules reviewed' },
  { id: 'excessive_inbound_rules', title: 'Excessive inbound firewall rules detected' },
  { id: 'any_any_inbound', title: 'Inbound firewall rule allows Any/Any' },
  { id: 'outdated_drivers', title: 'Outdated drivers detected' },
  { id: 'pending_reboot', title: 'Pending Windows reboot detected' },
];
